### ISSUE TITLE
Failure to compile - dependency argparse was updated

### ISSUE THREAD

**Issue by czipperz** [Machtan/cargo-linebreak#3]
When running `cargo install cargo-linebreak`, it was unable to find a viable package version for `argparse`.  The one located at https://github.com/Machtan/rust-argparse is version `0.3.0`, but you require `^0.2.2`.

**Comment by Machtan** [comment]
Uh. I'm not sure why this wouldn't work. Only if I've accidentally broken something. 

The problem with your suggestion is, that by using my own fork it isn't publishable to crates.io. 
I'll look into changing the argument parser to my own library, which might fix it. 

By the way, can you post the exact error you get? (I can't find 0.2.2 anywhere, and both Cargo.lock and Cargo.toml says '0.2.1' for me (as well as on crates.io)).

**Comment by Machtan** [comment]
I'm going to close this for now. Try installing the new version, and open an issue if that doesn't work either :)
